# The Battle of Neighborhoods (Week 1)

## Find Location for setting up Pet store in Bangkok, Thailand

### 1. BACKGROUND
Nowadays in Thailand, pets are a part of life. The society has joined the elderly. Older people have fewer children, making pets as friends or replacing them. The number of pets in Thailand grew and the benefits to the pet-related business is growing. 

Overall, the pet business in the year 2017 was valued at US$862 millions, growth up 10% from year 2016. The animal feed business has the largest share of 45%, followed by animal health care 32% and other related products such as clothing, accessories, toys 23%.

Pet store where to sale animal food and related products has 68% of market share and trend to growth up. This business is very interesting and a lot of opportunities. 

If someone looking for somewhere to open pet store in Bangkok. Can we recommend the potential place to open it?.

So, this project will find a the potential place for setting up the Pet Store. It helps to reduce time to find location and increase the chance of success.

### 2. DATA
Location is an important factor in doing business. Besides the convenient, then there are two things to consider. 

1. Customer demanding
   From the American Veterinary Medical Association(AVMA),
show the number of pet-owning households around 50% of number of household, more detail here https://www.avma.org/KB/Resources/Statistics/Pages/Market-research-statistics-US-pet-ownership.aspx
Although, no statistic report in Thailand, but it can concluded that number of household is associated with the number of pet-owning household. The area that high number of household is more demand in pet store than the area that low number of household. 

2. Competition 
    A lot of competitor in the area is effect to sales. So, if we find somewhere that less competitive it is good to do the business and increase chance of success. 

From above reason, we require

#### 2.1 Borough, Neighborhood and Coordinates(latitude/longitude)
Borough, Neighborhood and Coordinates(latitude/longitude) of Bangkok, got from here https://data.go.th/Default.aspx. It provided latitude/longitude data of city in Thailand.

In [2]:
import pandas as pd
import numpy as np
DF = pd.read_excel('data/TAMBON.xlsx')
DF.head(10)

,AD_LEVEL,TA_ID,TAMBON_T,TAMBON_E,AM_ID,AMPHOE_T,AMPHOE_E,CH_ID,CHANGWAT_T,CHANGWAT_E,LAT,LONG
0,4,370117,ต. ดอนเมย,Don Moei,3701,อ. เมืองอำนาจเจริญ,Mueang Amnat Charoen,37,จ. อำนาจเจริญ,Amnat Charoen,15.823,104.562
1,4,370702,ต. ดงมะยาง,Dong Mayang,3707,อ. ลืออำนาจ,Lue Amnat,37,จ. อำนาจเจริญ,Amnat Charoen,15.716,104.617
2,4,370701,ต. อำนาจ,Amnat,3707,อ. ลืออำนาจ,Lue Amnat,37,จ. อำนาจเจริญ,Amnat Charoen,15.710,104.668
3,4,370608,ต. รัตนวารี,Rattana Wari,3706,อ. หัวตะพาน,Hua Taphan,37,จ. อำนาจเจริญ,Amnat Charoen,15.723,104.513
4,4,370604,ต. หนองแก้ว,Nong Kaeo,3706,อ. หัวตะพาน,Hua Taphan,37,จ. อำนาจเจริญ,Amnat Charoen,15.696,104.531
5,4,370103,ต. นาจิก,Na Chik,3701,อ. เมืองอำนาจเจริญ,Mueang Amnat Charoen,37,จ. อำนาจเจริญ,Amnat Charoen,15.787,104.564
6,4,370601,ต. หัวตะพาน,Hua Taphan,3706,อ. หัวตะพาน,Hua Taphan,37,จ. อำนาจเจริญ,Amnat Charoen,15.718,104.457
7,4,370706,ต. แมด,Maet,3707,อ. ลืออำนาจ,Lue Amnat,37,จ. อำนาจเจริญ,Amnat Charoen,15.761,104.689
8,4,370506,ต. หนองสามสี,Nong Sam Si,3705,อ. เสนางคนิคม,Senangkhanikhom,37,จ. อำนาจเจริญ,Amnat Charoen,16.050,104.616
9,4,370110,ต. นาวัง,Na Wang,3701,อ. เมืองอำนาจเจริญ,Mueang Amnat Charoen,37,จ. อำนาจเจริญ,Amnat Charoen,15.997,104.579

##### Understand the data set: Each column is represented 
      - TA_ID       is Neighborhood ID
      - TAMBON_E    is Neighborhood Name in English
      - TAMBON_T    is Neighborhood Name in Thai
      - AM_ID       is Borough ID
      - AMPHOE_E    is Borough Name in English
      - AMPHOE_T    is Borough Name in Thai
      - CH_ID       is City ID
      - CHANGWAT_E  is CITY Name in English
      - CHANGWAT_T  is CITY Namein Thai
      
We prepare data set follow these
1. Select 'Bangkok' 
2. Select column 'TA_ID', 'TAMBON_E','AMPHOE_E', 'LAT', 'LONG'
3. Change column_name 
      - TA_ID      to NBH_ID
      - TAMBON_E   to Neigborhood
      - AMPHOE_E   to Borough
      - LAT        to latitude
      - LONG       to longitude

In [3]:
# Select 'Bangkok'
DF = DF[DF['CHANGWAT_E'] == 'Bangkok']
# Select column
BKKDF = pd.DataFrame(DF[['TA_ID', 'AMPHOE_E','TAMBON_E', 'LAT','LONG']])
#.copy()
# Change column_name
columns = ['NBH_ID', 'Borough', 'Neighborhood',  'Latitude', 'Longitude']
BKKDF.columns = [columns]                                       
BKKDF = BKKDF.reset_index(drop = True)
BKKDF.head(10)

   NBH_ID              Borough      Neighborhood Latitude Longitude
0  100106          Phra Nakhon      Sao Chingcha   13.753   100.500
1  100105          Phra Nakhon  San Chaopho Suea   13.754   100.497
2  100108          Phra Nakhon         Talat Yot   13.760   100.498
3  100103          Phra Nakhon  Wat Ratchabophit   13.750   100.499
4  100104          Phra Nakhon        Samran Rat   13.751   100.503
5  100109          Phra Nakhon   Chana Songkhram   13.762   100.495
6  100204                Dusit  Si Yaek Maha Nak   13.758   100.517
7  100804  Pom Prap Sattruphai          Ban Bath   13.752   100.507
8  100110          Phra Nakhon     Ban Phan Thom   13.762   100.503
9  101303       Samphanthawong         Talat Noi   13.734   100.513

In [4]:
print ('Nunber of Borough = ', BKKDF['Borough'].nunique())
print ('Number of Neighborhood = ', BKKDF['Neighborhood'].nunique())

Nunber of Borough =  Borough    50
dtype: int64
Number of Neighborhood =  Neighborhood    154
dtype: int64

#### 2.2 Number of Household
Number of Household divide by neighbor got from here
http://stat.bora.dopa.go.th/new_stat/webPage/statByYear.php

In [5]:
import pandas as pd 
NumHouseDF = pd.read_excel('data/POP.xlsx') 
NumHouseDF.head(10)

    TA_ID  MALE  FEMALE  TOTAL  HOUSEHOLD
0  100101  2358    1595   3953       1245
1  100102  5911    5516  11427       5361
2  100103  1489    1825   3314        984
3  100104  1710    1611   3321       1139
4  100105  1404    1874   3278        998
5  100106  1064    1228   2292        704
6  100107  2127    2710   4837       1615
7  100108  1116    1371   2487       1193
8  100109   943    1025   1968        829
9  100110  2972    3841   6813       2034

In [6]:
# Select column
HDF = NumHouseDF[['TA_ID', 'TOTAL','HOUSEHOLD']].copy()
# Change column_name
columns = ['NBH_ID', 'Population', 'Household']
HDF.columns = [columns]                      
HDF.head(5)

   NBH_ID Population Household
0  100101       3953      1245
1  100102      11427      5361
2  100103       3314       984
3  100104       3321      1139
4  100105       3278       998

In [7]:
print ('Number of Neighborhood = ', HDF['NBH_ID'].nunique())

Number of Neighborhood =  NBH_ID    154
dtype: int64

#### 2.3 Venues from Foursquare
From Borough, Neighborhood and Coordinates (latitude/longitude) in 2.1, we will request and get venues from Foursquare in each Neighbor and consider venues category name : 'Pet Store' / 'Pet Service'

In [41]:
!conda install -c conda-forge geopy --yes
!conda install -c conda-forge folium=0.5.0 --yes
print('Install Done.')

Solving environment: done

## Package Plan ##

  environment location: /home/jupyterlab/conda

  added / updated specs:
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2p             |       h470a237_1         3.1 MB  conda-forge
    geopy-1.17.0               |             py_0          49 KB  conda-forge
    certifi-2018.11.29         |        py36_1000         145 KB  conda-forge
    conda-4.5.11               |        py36_1000         651 KB  conda-forge
    ca-certificates-2018.11.29 |       ha4d7672_0         143 KB  conda-forge
    geographiclib-1.49         |             py_0          32 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.1 MB

The following NEW packages will be INSTALLED:

    geographiclib:   1.49-py_0            conda-forge
    geopy:           1.17.0-py_0          conda-forge

The following packages will be UPDATED:

    ca-certificates: 2018.8.24-ha4d7672_0 conda-forge --> 2018.11.29-ha4d7672_0 conda-forge
    certifi:         2018.8.24-py36_1001  conda-forge --> 2018.11.29-py36_1000  conda-forge
    conda:           4.5.11-py36_0        conda-forge --> 4.5.11-py36_1000      conda-forge
    openssl:         1.0.2p-h470a237_0    conda-forge --> 1.0.2p-h470a237_1     conda-forge


Downloading and Extracting Packages
openssl-1.0.2p       | 3.1 MB    | ##################################### | 100%
geopy-1.17.0         | 49 KB     | ##################################### | 100%
certifi-2018.11.29   | 145 KB    | ##################################### | 100%
conda-4.5.11         | 651 KB    | ##################################### | 100%
ca-certificates-2018 | 143 KB    | ##################################### | 100%
geographiclib-1.49   | 32 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done

## Package Plan ##

  environment location: /home/jupyterlab/conda

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.14.2               |   py36hdbf6ddf_0         4.0 MB
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    branca-0.3.1               |             py_0          25 KB  conda-forge
    pandas-0.23.4              |   py36hf8a1672_0        27.8 MB  conda-forge
    altair-2.2.2               |        py36_1001         494 KB  conda-forge
    folium-0.5.0               |             py_0          45 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        32.4 MB

The following NEW packages will be INSTALLED:

    altair:  2.2.2-py36_1001       conda-forge
    branca:  0.3.1-py_0            conda-forge
    folium:  0.5.0-py_0            conda-forge
    vincent: 0.4.4-py_1            conda-forge

The following packages will be UPDATED:

    pandas:  0.23.0-py36h637b7d7_0             --> 0.23.4-py36hf8a1672_0 conda-forge

The following packages will be DOWNGRADED:

    numpy:   1.14.3-py36hcd700cb_1             --> 1.14.2-py36hdbf6ddf_0


Downloading and Extracting Packages
numpy-1.14.2         | 4.0 MB    | ##################################### | 100%
vincent-0.4.4        | 28 KB     | ##################################### | 100%
branca-0.3.1         | 25 KB     | ##################################### | 100%
pandas-0.23.4        | 27.8 MB   | ##################################### | 100%
altair-2.2.2         | 494 KB    | ##################################### | 100%
folium-0.5.0         | 45 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Install Done.

In [8]:
import json 
from geopy.geocoders import Nominatim 
import requests 
from pandas.io.json import json_normalize 
import matplotlib.cm as cm
import matplotlib.colors as colors
from sklearn.cluster import KMeans
import folium 
print('Libraries imported.')

Libraries imported.

In [9]:
CLIENT_ID = 'GMWUCCBSTVJ0FWQMEWXKSBAUFNBP2DDTDDIS4PV4GKGOKV2L' # your Foursquare ID
CLIENT_SECRET = 'NNYNVNHKHD55AXIRDF4PCZTCOLUMCBOFAYA3GQCT04P5AIAQ' # your Foursquare Secret
VERSION = '20180604'

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: GMWUCCBSTVJ0FWQMEWXKSBAUFNBP2DDTDDIS4PV4GKGOKV2L
CLIENT_SECRET:NNYNVNHKHD55AXIRDF4PCZTCOLUMCBOFAYA3GQCT04P5AIAQ

#### function to the venues from all neighborhoods in Bangkok

In [10]:
def getNearbyVenues(names, latitudes, longitudes, radius):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()['response']['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues )

#### Get venues

In [11]:
LIMIT = 1000
BKK_venues = getNearbyVenues(names = BKKDF.iloc[:, 2], latitudes = BKKDF.iloc[ : , 3], longitudes = BKKDF.iloc[ : ,4], radius = 5000)

Sao Chingcha
San Chaopho Suea
Talat Yot
Wat Ratchabophit
Samran Rat
Chana Songkhram
Si Yaek Maha Nak
Ban Bath
Ban Phan Thom
Talat Noi
Wat Thep Si Rin
Bang Khun Phrom
Wat Som Manut
Samphuntawong
Bowon Niwet
Si Phraya
Chakawat
Wat Sam Phraya
Khlong Mahadthai
Bang Rak
Pom Prap
Maha Prutharam
Hirunruji
Somdej Choa Phraya
Wang Burapha Phirom
Wat Kanlaya
Silom
Kuhasawan
Wat Arun
Khlongsarn
Makasan
Bang Jak
Khlong Rakphra
Wachira Phayaban
Rong Mueang
Thanon Phayathai
Bang Yi Rua
Wangmai
Siriraj
Wat Phrayakai
Suriwong
Phra Borom Maha Ratchawang
Talat Phu
Bang Khunnon
Pak Khlong Phasi Chareon
Suan Chitlada
Khlong Ton Si
Khlongton
Thung Watdon
Pathum Wan
Bang Kho Laem
Klong Teoi Nua
Ban Changlor
Yarn Nava
Dusit
Bang Bumru
Banglampu Lang
Thanon Petchburi
Thung Phayathai
Khlong Kwang
Bang Kloa
Bang Yi Khan
Arun Amarin
Thung Mahamek
Bang Wak
Bang Or
Bang Phlat
Lumpini
Bang Duan
Phrakanong Nua
Phrakanong
Bang Khun Si
Bang Chuang Nung
Bookalo
Bang Khoa
Huai Khwang
Bang Phom
Jomthong
Samsean Nok
Wat Tha Phra
Chongnonsi
Rat burana
Thanon Nakornchaisi
Talat Bangkean
Jorakaebua
Bangkapi
Taling Chan
Bang Wa
Bang Khun Thein
Bang Phong Phang
Bang Pakok
Khlongton Nua
Khlong Toei
Bangmod
Din Daeng
Samsean Nai
ChimPhee
Luk Song
Bang Ramad
Sai Kong Din
Lat Krabang
Bangkhae
Bangkhae Nua
Bang Mod
Khlong Jan
Khlong Thanon
Nong Bon
Bang Su
Bang Jak Phra
Lat Phroa
Au Nerng
Hua Mark
Sai Mai
Bang Phai
Khlong Song Ton Nun
Dok Mai
Khu Fung Nua
Bang Na
Nong Kang Phu
Thung Song Hong
Wang Thong Lang
Khlong Sam Phavet
Anusoavaree
Sai Kong Din Tai
Thawi Watthana
Nong Khaem
Bang Chan
Thung Khu
Kok Fad
Tha Rang
Khlong Kum
Thub Yoa
Khum Thong
Suan Luang
Khlong Sib
Prawet
Min buri
Khanna Yoa
Sam Wa Tawantok
Saphan Sung
Lum Toyting
Sala Thammasarn
Lum Pakshee
Latyoa
Lumphatu
Nong Chok
Bang Bon
San Sab
Si kun
Khatumlai
Sam Wa Tawanook
Khlong Sib Song
Sam Dum
Tha Kham

#### check the size of the resulting venues dataframe

In [12]:
print(BKK_venues.shape)
BKK_venues.head(30)

(14275, 7)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Sao Chingcha,13.753,100.5,Mont Nom Sod (มนต์นมสด),13.754160,100.501384,Bakery
1,Sao Chingcha,13.753,100.5,Ko Panich (ก.พานิช),13.752201,100.498250,Dessert Shop
2,Sao Chingcha,13.753,100.5,Nattaporn Ice cream (นัฐพร ไอศครีมกะทิสดแท้),13.751772,100.497527,Ice Cream Shop
3,Sao Chingcha,13.753,100.5,ศิริพรโภชนา,13.753320,100.500880,Thai Restaurant
4,Sao Chingcha,13.753,100.5,Krua Apsorn (ครัวอัปษร),13.755290,100.501541,Thai Restaurant
5,Sao Chingcha,13.753,100.5,Once Again Hostel,13.752927,100.503447,Hostel
6,Sao Chingcha,13.753,100.5,Here Hostel,13.755642,100.503648,Hostel
7,Sao Chingcha,13.753,100.5,Thip Samai (ทิพย์สมัย (ผัดไทยประตูผี)),13.752800,100.504778,Noodle House
8,Sao Chingcha,13.753,100.5,Temple of the Emerald Buddha (วัดพระศรีรัตนศาส...,13.751735,100.492651,Buddhist Temple
9,Sao Chingcha,13.753,100.5,Passport Book Shop (ร้านหนังสือเดินทาง),13.758152,100.504014,Bookstore
10,Sao Chingcha,13.753,100.5,หอศิลป์ สมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินี...,13.756267,100.504884,Art Gallery
11,Sao Chingcha,13.753,100.5,The Club,13.759390,100.496815,Nightclub
12,Sao Chingcha,13.753,100.5,On Lok Yun (ออน ล๊อก หยุ่น),13.747065,100.500606,Breakfast Spot
13,Sao Chingcha,13.753,100.5,The Grand Palace (พระบรมมหาราชวัง),13.751546,100.491934,Palace
14,Sao Chingcha,13.753,100.5,Pai Spa (ปัยย์สปา บ้านรามบุตรี),13.759522,100.498694,Spa
15,Sao Chingcha,13.753,100.5,Shewa Spa (ชีวา สปา),13.759412,100.498301,Spa
16,Sao Chingcha,13.753,100.5,Dusit Maha Prasat Throne Hall (พระที่นั่งดุสิต...,13.750105,100.490524,Palace
17,Sao Chingcha,13.753,100.5,ต้มยำกุ้ง บางลำภู,13.760900,100.498337,Thai Restaurant
18,Sao Chingcha,13.753,100.5,Adhere the 13th Blues Bar,13.763043,100.498839,Jazz Club
19,Sao Chingcha,13.753,100.5,Ku Bar,13.758810,100.503642,Cocktail Bar
20,Sao Chingcha,13.753,100.5,Nakhon Sanook (ข้าวหมูแดง นครสนุก),13.747888,100.507420,Asian Restaurant
21,Sao Chingcha,13.753,100.5,Wat Pho Thai Traditional Medical and Massage S...,13.746596,100.494100,Massage Studio
22,Sao Chingcha,13.753,100.5,The National Theatre (โรงละครแห่งชาติ),13.758806,100.492861,Theater
23,Sao Chingcha,13.753,100.5,Massage In Garden,13.762363,100.495126,Massage Studio
24,Sao Chingcha,13.753,100.5,Riva Surya Bangkok,13.762308,100.493020,Hotel
25,Sao Chingcha,13.753,100.5,คุณแดงก๋วยจั๊บญวน,13.762159,100.493718,Vietnamese Restaurant
26,Sao Chingcha,13.753,100.5,Museum Siam (มิวเซียมสยาม),13.743906,100.493877,History Museum
27,Sao Chingcha,13.753,100.5,Starbucks (สตาร์บัคส์),13.754670,100.488694,Coffee Shop
28,Sao Chingcha,13.753,100.5,Home Café Tha Tien (โฮม คาเฟ่ ท่าเตียน),13.745735,100.491391,Café
29,Sao Chingcha,13.753,100.5,Tha Prachan (ท่าพระจันทร์),13.756201,100.489682,Neighborhood

### Now we get all Data !!!!!!!

#### 2.4 How to find the Potential Location
After request, get and merge all dataset together, we will get table of number of Pet Store and number of Household by each Neighborhood. To find the potential location, use the Competitive ratio as follows.
     
#### Competitive ratio = (number of Pet Store)/(number of HouseHold)

High Competitive ratio means high competition, in the oppoeite, low Competitive ratio means low competition.

We will compare this ratio and select Neighborhood which lowest ratio to recommend to setup Pet Store.

### WE will find this in week 2 !!!!!!!!